sudo: required
language: minimal
env:
    - SWIFT_VERSION=swift-5.1.1
install:
    - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

jobs:
  include:
    - os: osx
      osx_image: xcode11.1
    - os: osx
      osx_image: xcode11.2
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial

script:
    - swift build
    - swift build -c release
    - swift test